package compiler.lexer;

public enum TokenType {
    LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE,
    COMMA, SEMICOLON,

    PLUS, MINUS, STAR, SLASH, PERCENT,
    BANG, BANG_EQUAL,
    EQUAL, EQUAL_EQUAL,
    GREATER, GREATER_EQUAL, LESS, LESS_EQUAL,
    AND, OR,

    IDENTIFIER, NUMBER, STRING,

    LET, IF, ELSE, WHILE, FOR, FUNCTION, RETURN, PRINT,
    TRUE, FALSE, NIL,

    EOF
}
